apiVersion: v1
kind: Service
metadata:
  name: nest-k8-demo
  namespace: app-service
spec:
  selector:
    app: nest-k8-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
